### ISSUE TITLE
Document building your own

### ISSUE THREAD

**Issue by AGhost-7** [AGhost-7/docker-dev#51]
- [x] Document benefits of containerizing environment.
- [x] Minimal tmux setup (no powerline).
- [ ] Clipboard
- [x] From ubuntu:xenial, how to install basic tooling (git, ssh, curl, man, etc).
- [x] Minimal, language agnostic vim setup.
- [x] Specialize for a particular stack (nodejs web development).
- [ ] docker and compose

**Comment by AGhost-7** [comment]
@hardy613 maybe you could document the nodejs web development part that you did for your image.

**Comment by shardy613** [comment]
sure, where should I put it for you

**Comment by AGhost-7** [comment]
Crossed off, thanks.

**Comment by AGhost-7** [comment]
Closing, I no longer recommend using docker inside of the development container unless inside of a virtual machine.
