### ISSUE TITLE
RFC - Deno image

### ISSUE THREAD

**Issue by hardy613** [AGhost-7/docker-dev#69]
https://github.com/denoland/deno_install

is it worth adding this?

**Comment by AGhost-7** [comment]
I am willing to add support for deno, however I think it should be a separate image from `nodejs-dev`. There's probably not enough overlap with what is included in `nodejs-dev` to put deno in the same image.

**Comment by hardy613** [comment]
I think that makes sense, deno should not need npm to stand up. Would you perfer this be set up like the npm images, I ask because there is only one release of deno but you can install specific version.

**Comment by hardy613** [comment]
closed #71
